/*
 * miniext conformance suite.
 *
 * Runs against the data disk built from the generated staging tree:
 *
 *     test/miniext-stage.py build/miniext-stage
 *     scripts/mkdata.sh build/data.img build/miniext-stage 64M
 *     make app=tests && scripts/run.py --emulated-nvme build/data.img
 *
 * The expected sizes and checksums below are the host's view of that staging
 * tree, so a mismatch means miniext read something different from what
 * mkfs.ext4 wrote -- which is the whole point of the exercise.
 *
 * Skips itself (rather than failing) when no second NVMe device is attached.
 */

#include <cerrno>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

#include "modules/miniext/miniext.hh"

namespace {

int failures;
int checks;

void check(bool ok, const char *what)
{
    checks++;
    if (!ok) {
        failures++;
        printf("  FAIL  %s\n", what);
    } else {
        printf("  PASS  %s\n", what);
    }
}

// FNV-1a, matched by the host-side generator so content can be compared
// without shipping the files into the image.
uint64_t fnv1a(const uint8_t *p, size_t n, uint64_t h = 0xcbf29ce484222325ull)
{
    for (size_t i = 0; i < n; i++) {
        h ^= p[i];
        h *= 0x100000001b3ull;
    }
    return h;
}

struct expected_file {
    const char *path;
    uint64_t size;
    uint64_t fnv;
};

// Generated by test/miniext-stage.py --table; regenerate if the tree changes.
const expected_file expected[] = {
    {"/db/hello.txt",      19,      0x7ec9fb48535420a7ull},
    {"/db/big.bin",        1600000, 0xd42fbe3dc27b1fd5ull},
    {"/db/odd.bin",        4356,    0x841b0198fe38cd23ull},
    {"/db/sub/nested.txt", 12,      0x74d8b4e88487b9d6ull},
};

// Read a whole file through pread in `chunk`-sized pieces and checksum it.
// Varying the chunk size exercises block-aligned and straddling reads.
bool read_and_check(const expected_file &e, size_t chunk)
{
    int err = 0;
    miniext::file *f = miniext::open(e.path, miniext::O_RD, &err);
    if (!f) {
        printf("        open(%s) failed: %d\n", e.path, err);
        return false;
    }

    if (miniext::size(f) != e.size) {
        printf("        %s: size %lu, expected %lu\n", e.path,
               (unsigned long)miniext::size(f), (unsigned long)e.size);
        miniext::close(f);
        return false;
    }

    std::vector<uint8_t> buf(chunk);
    uint64_t h = 0xcbf29ce484222325ull;
    uint64_t off = 0;
    for (;;) {
        int64_t got = miniext::pread(f, buf.data(), chunk, off);
        if (got < 0) {
            printf("        %s: pread at %lu failed: %ld\n", e.path,
                   (unsigned long)off, (long)got);
            miniext::close(f);
            return false;
        }
        if (got == 0) {
            break;
        }
        h = fnv1a(buf.data(), got, h);
        off += got;
    }
    miniext::close(f);

    if (off != e.size) {
        printf("        %s: read %lu bytes, expected %lu\n", e.path,
               (unsigned long)off, (unsigned long)e.size);
        return false;
    }
    if (h != e.fnv) {
        printf("        %s: checksum 0x%016lx, expected 0x%016lx\n", e.path,
               (unsigned long)h, (unsigned long)e.fnv);
        return false;
    }
    return true;
}

} // namespace

int os_miniext_main()
{
    printf("======== miniext ========\n");
    failures = 0;
    checks = 0;

    int rc = miniext::mount(1, "/db");
    if (rc == -ENODEV) {
        printf("  SKIP  no second NVMe device attached\n");
        printf("        run with: scripts/run.py --emulated-nvme build/data.img\n");
        printf("======== miniext: skipped ========\n");
        return 0;
    }
    check(rc == 0, "mount nvme1 at /db");
    if (rc != 0) {
        printf("======== miniext: FAILED (%d/%d) ========\n", failures, checks);
        return 1;
    }

    miniext::fs_info fi;
    if (miniext::info(&fi) == 0) {
        printf("        %u-byte blocks, %lu blocks, %u inodes, %u groups\n",
               fi.block_size, (unsigned long)fi.block_count, fi.inode_count,
               fi.group_count);
    }

    // --- directory listing ---
    std::vector<std::string> names;
    rc = miniext::list("/db", [&](const char *n, bool) { names.push_back(n); });
    check(rc == 0, "list /db");

    auto has = [&](const char *n) {
        for (auto &s : names) {
            if (s == n) return true;
        }
        return false;
    };
    check(has("hello.txt"), "/db contains hello.txt");
    check(has("big.bin"), "/db contains big.bin");
    check(has("odd.bin"), "/db contains odd.bin");
    check(has("sub"), "/db contains sub");
    check(!has("."), "listing skips . and ..");

    names.clear();
    rc = miniext::list("/db/sub", [&](const char *n, bool) { names.push_back(n); });
    check(rc == 0 && names.size() == 1 && names[0] == "nested.txt",
          "list /db/sub finds nested.txt");

    // --- metadata ---
    check(miniext::exists("/db/hello.txt"), "exists(/db/hello.txt)");
    check(!miniext::exists("/db/nope.txt"), "!exists(/db/nope.txt)");
    check(miniext::is_directory("/db/sub"), "is_directory(/db/sub)");
    check(!miniext::is_directory("/db/hello.txt"), "!is_directory(/db/hello.txt)");

    uint64_t sz = 0;
    check(miniext::file_size("/db/big.bin", &sz) == 0 && sz == 1600000,
          "file_size(/db/big.bin) == 1600000");

    // --- content, at several chunk sizes ---
    // 4096 is block-aligned; 4096 exercises whole-block direct reads; 1000 and
    // 5000 straddle block boundaries in both directions.
    for (size_t chunk : {(size_t)4096, (size_t)1000, (size_t)5000, (size_t)65536}) {
        for (const auto &e : expected) {
            char what[160];
            snprintf(what, sizeof(what), "read %s in %zu-byte chunks", e.path, chunk);
            check(read_and_check(e, chunk), what);
        }
    }

    // --- unaligned positional reads against a known pattern ---
    // big.bin is "%08d" repeated, so byte N is digit N%8 of the number N/8.
    {
        int err = 0;
        miniext::file *f = miniext::open("/db/big.bin", miniext::O_RD, &err);
        check(f != nullptr, "open /db/big.bin for positional reads");
        if (f) {
            bool ok = true;
            const uint64_t offsets[] = {0, 1, 4095, 4096, 4097, 8191, 100000, 1599990};
            for (uint64_t off : offsets) {
                uint8_t got[16];
                int64_t n = miniext::pread(f, got, sizeof(got), off);
                if (n < 0) { ok = false; break; }
                for (int64_t i = 0; i < n; i++) {
                    const uint64_t pos = off + i;
                    // Expected byte: digit (pos%8) of "%08d" applied to pos/8.
                    char num[16];
                    snprintf(num, sizeof(num), "%08d", (int)(pos / 8));
                    if (got[i] != (uint8_t)num[pos % 8]) {
                        printf("        big.bin[%lu] = 0x%02x, expected '%c'\n",
                               (unsigned long)pos, got[i], num[pos % 8]);
                        ok = false;
                        break;
                    }
                }
                if (!ok) break;
            }
            check(ok, "unaligned positional reads match the generator pattern");

            // Reading at and past EOF.
            uint8_t tmp[8];
            check(miniext::pread(f, tmp, sizeof(tmp), 1600000) == 0, "pread at EOF returns 0");
            check(miniext::pread(f, tmp, sizeof(tmp), 1700000) == 0, "pread past EOF returns 0");
            check(miniext::pread(f, tmp, sizeof(tmp), 1599996) == 4, "pread clipped to EOF");
            miniext::close(f);
        }
    }

    // --- error paths ---
    {
        int err = 0;
        check(miniext::open("/db/nope.txt", miniext::O_RD, &err) == nullptr &&
              err == -ENOENT, "open of a missing file gives ENOENT");
        err = 0;
        check(miniext::open("/db/sub", miniext::O_RD, &err) == nullptr &&
              err == -EISDIR, "open of a directory gives EISDIR");
        err = 0;
        check(miniext::open("/elsewhere/x", miniext::O_RD, &err) == nullptr,
              "open outside the mount point fails");
        err = 0;
        check(miniext::open("/db/hello.txt/x", miniext::O_RD, &err) == nullptr &&
              err == -ENOTDIR, "descending through a file gives ENOTDIR");
    }

    check(miniext::umount() == 0, "umount");

    if (failures) {
        printf("======== miniext: FAILED (%d of %d checks) ========\n", failures, checks);
        return 1;
    }
    printf("======== miniext: all %d checks passed ========\n", checks);
    return 0;
}
