/*
 * miniext conformance suite.
 *
 * Runs against the data disk built from the generated staging tree:
 *
 *     test/miniext-stage.py build/miniext-stage
 *     scripts/mkdata.sh build/data.img build/miniext-stage 64M
 *     make app=tests && scripts/run.py --emulated-nvme build/data.img
 *
 * The expected sizes and checksums below are the host's view of that staging
 * tree, so a mismatch means miniext read something different from what
 * mkfs.ext4 wrote -- which is the whole point of the exercise.
 *
 * Skips itself (rather than failing) when no second NVMe device is attached.
 */

#include <cerrno>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

#include <osv/mem/pagecache.hh>
#include <osv/mem/store.hh>

#include "modules/miniext/miniext.hh"

namespace {

int failures;
int checks;

void check(bool ok, const char *what)
{
    checks++;
    if (!ok) {
        failures++;
        printf("  FAIL  %s\n", what);
    } else {
        printf("  PASS  %s\n", what);
    }
}

// FNV-1a, matched by the host-side generator so content can be compared
// without shipping the files into the image.
uint64_t fnv1a(const uint8_t *p, size_t n, uint64_t h = 0xcbf29ce484222325ull)
{
    for (size_t i = 0; i < n; i++) {
        h ^= p[i];
        h *= 0x100000001b3ull;
    }
    return h;
}

struct expected_file {
    const char *path;
    uint64_t size;
    uint64_t fnv;
};

// Generated by test/miniext-stage.py --table; regenerate if the tree changes.
const expected_file expected[] = {
    {"/db/hello.txt",      19,      0x7ec9fb48535420a7ull},
    {"/db/big.bin",        1600000, 0xd42fbe3dc27b1fd5ull},
    {"/db/odd.bin",        4356,    0x841b0198fe38cd23ull},
    {"/db/sub/nested.txt", 12,      0x74d8b4e88487b9d6ull},
};

// Read a whole file through pread in `chunk`-sized pieces and checksum it.
// Varying the chunk size exercises block-aligned and straddling reads.
bool read_and_check(const expected_file &e, size_t chunk)
{
    int err = 0;
    miniext::file *f = miniext::open(e.path, miniext::O_RD, &err);
    if (!f) {
        printf("        open(%s) failed: %d\n", e.path, err);
        return false;
    }

    if (miniext::size(f) != e.size) {
        printf("        %s: size %lu, expected %lu\n", e.path,
               (unsigned long)miniext::size(f), (unsigned long)e.size);
        miniext::close(f);
        return false;
    }

    std::vector<uint8_t> buf(chunk);
    uint64_t h = 0xcbf29ce484222325ull;
    uint64_t off = 0;
    for (;;) {
        int64_t got = miniext::pread(f, buf.data(), chunk, off);
        if (got < 0) {
            printf("        %s: pread at %lu failed: %ld\n", e.path,
                   (unsigned long)off, (long)got);
            miniext::close(f);
            return false;
        }
        if (got == 0) {
            break;
        }
        h = fnv1a(buf.data(), got, h);
        off += got;
    }
    miniext::close(f);

    if (off != e.size) {
        printf("        %s: read %lu bytes, expected %lu\n", e.path,
               (unsigned long)off, (unsigned long)e.size);
        return false;
    }
    if (h != e.fnv) {
        printf("        %s: checksum 0x%016lx, expected 0x%016lx\n", e.path,
               (unsigned long)h, (unsigned long)e.fnv);
        return false;
    }
    return true;
}

} // namespace

int os_miniext_main()
{
    printf("======== miniext ========\n");
    failures = 0;
    checks = 0;

    int rc = miniext::mount(1, "/db");
    if (rc == -ENODEV) {
        printf("  SKIP  no second NVMe device attached\n");
        printf("        run with: scripts/run.py --emulated-nvme build/data.img\n");
        printf("======== miniext: skipped ========\n");
        return 0;
    }
    check(rc == 0, "mount nvme1 at /db");
    if (rc != 0) {
        printf("======== miniext: FAILED (%d/%d) ========\n", failures, checks);
        return 1;
    }

    miniext::fs_info fi;
    if (miniext::info(&fi) == 0) {
        printf("        %u-byte blocks, %lu blocks, %u inodes, %u groups\n",
               fi.block_size, (unsigned long)fi.block_count, fi.inode_count,
               fi.group_count);
    }

    // --- directory listing ---
    std::vector<std::string> names;
    rc = miniext::list("/db", [&](const char *n, bool) { names.push_back(n); });
    check(rc == 0, "list /db");

    auto has = [&](const char *n) {
        for (auto &s : names) {
            if (s == n) return true;
        }
        return false;
    };
    check(has("hello.txt"), "/db contains hello.txt");
    check(has("big.bin"), "/db contains big.bin");
    check(has("odd.bin"), "/db contains odd.bin");
    check(has("sub"), "/db contains sub");
    check(!has("."), "listing skips . and ..");

    names.clear();
    rc = miniext::list("/db/sub", [&](const char *n, bool) { names.push_back(n); });
    check(rc == 0 && names.size() == 1 && names[0] == "nested.txt",
          "list /db/sub finds nested.txt");

    // --- metadata ---
    check(miniext::exists("/db/hello.txt"), "exists(/db/hello.txt)");
    check(!miniext::exists("/db/nope.txt"), "!exists(/db/nope.txt)");
    check(miniext::is_directory("/db/sub"), "is_directory(/db/sub)");
    check(!miniext::is_directory("/db/hello.txt"), "!is_directory(/db/hello.txt)");

    uint64_t sz = 0;
    check(miniext::file_size("/db/big.bin", &sz) == 0 && sz == 1600000,
          "file_size(/db/big.bin) == 1600000");

    // --- content, at several chunk sizes ---
    // 4096 is block-aligned; 4096 exercises whole-block direct reads; 1000 and
    // 5000 straddle block boundaries in both directions.
    for (size_t chunk : {(size_t)4096, (size_t)1000, (size_t)5000, (size_t)65536}) {
        for (const auto &e : expected) {
            char what[160];
            snprintf(what, sizeof(what), "read %s in %zu-byte chunks", e.path, chunk);
            check(read_and_check(e, chunk), what);
        }
    }

    // --- unaligned positional reads against a known pattern ---
    // big.bin is "%08d" repeated, so byte N is digit N%8 of the number N/8.
    {
        int err = 0;
        miniext::file *f = miniext::open("/db/big.bin", miniext::O_RD, &err);
        check(f != nullptr, "open /db/big.bin for positional reads");
        if (f) {
            bool ok = true;
            const uint64_t offsets[] = {0, 1, 4095, 4096, 4097, 8191, 100000, 1599990};
            for (uint64_t off : offsets) {
                uint8_t got[16];
                int64_t n = miniext::pread(f, got, sizeof(got), off);
                if (n < 0) { ok = false; break; }
                for (int64_t i = 0; i < n; i++) {
                    const uint64_t pos = off + i;
                    // Expected byte: digit (pos%8) of "%08d" applied to pos/8.
                    char num[16];
                    snprintf(num, sizeof(num), "%08d", (int)(pos / 8));
                    if (got[i] != (uint8_t)num[pos % 8]) {
                        printf("        big.bin[%lu] = 0x%02x, expected '%c'\n",
                               (unsigned long)pos, got[i], num[pos % 8]);
                        ok = false;
                        break;
                    }
                }
                if (!ok) break;
            }
            check(ok, "unaligned positional reads match the generator pattern");

            // Reading at and past EOF.
            uint8_t tmp[8];
            check(miniext::pread(f, tmp, sizeof(tmp), 1600000) == 0, "pread at EOF returns 0");
            check(miniext::pread(f, tmp, sizeof(tmp), 1700000) == 0, "pread past EOF returns 0");
            check(miniext::pread(f, tmp, sizeof(tmp), 1599996) == 4, "pread clipped to EOF");
            miniext::close(f);
        }
    }

    // --- error paths ---
    {
        int err = 0;
        check(miniext::open("/db/nope.txt", miniext::O_RD, &err) == nullptr &&
              err == -ENOENT, "open of a missing file gives ENOENT");
        err = 0;
        check(miniext::open("/db/sub", miniext::O_RD, &err) == nullptr &&
              err == -EISDIR, "open of a directory gives EISDIR");
        err = 0;
        check(miniext::open("/elsewhere/x", miniext::O_RD, &err) == nullptr,
              "open outside the mount point fails");
        err = 0;
        check(miniext::open("/db/hello.txt/x", miniext::O_RD, &err) == nullptr &&
              err == -ENOTDIR, "descending through a file gives ENOTDIR");
    }

    // --- write path -----------------------------------------------------
    // Everything below is checked again from the host with fsck.ext4 -f -n
    // after the run; a clean bill there is the real gate, not these checks.
    {
        int err = 0;
        miniext::file *f = miniext::open("/db/written.bin",
                                         miniext::O_RDWR | miniext::O_CREATE, &err);
        check(f != nullptr, "create /db/written.bin");
        if (f) {
            // Small write, read back through a fresh open.
            const char *msg = "miniext write path\n";
            const size_t mlen = strlen(msg);
            check(miniext::pwrite(f, msg, mlen, 0) == (int64_t)mlen, "pwrite small");
            check(miniext::size(f) == mlen, "size after small write");

            char back[64] = {};
            check(miniext::pread(f, back, mlen, 0) == (int64_t)mlen &&
                  memcmp(back, msg, mlen) == 0, "read back small write");

            // Grow across many blocks so the extent tree has to grow too.
            std::vector<uint8_t> chunk(64 * 1024);
            for (size_t i = 0; i < chunk.size(); i++) {
                chunk[i] = (uint8_t)(i * 31 + 7);
            }
            bool ok = true;
            for (int i = 0; i < 40; i++) {          // 2.5 MiB
                int64_t n = miniext::pwrite(f, chunk.data(), chunk.size(),
                                            (uint64_t)i * chunk.size());
                if (n != (int64_t)chunk.size()) { ok = false; break; }
            }
            check(ok, "pwrite 2.5 MiB across many extents");
            check(miniext::size(f) == 40ull * chunk.size(), "size after bulk write");

            // Verify every byte came back.
            std::vector<uint8_t> rb(chunk.size());
            ok = true;
            for (int i = 0; i < 40 && ok; i++) {
                int64_t n = miniext::pread(f, rb.data(), rb.size(),
                                           (uint64_t)i * chunk.size());
                if (n != (int64_t)rb.size() || memcmp(rb.data(), chunk.data(), rb.size()) != 0) {
                    ok = false;
                }
            }
            check(ok, "read back 2.5 MiB");

            // Unaligned write straddling a block boundary.
            const char *tag = "STRADDLE";
            check(miniext::pwrite(f, tag, 8, 4090) == 8, "pwrite straddling a block");
            char tb[8] = {};
            check(miniext::pread(f, tb, 8, 4090) == 8 && memcmp(tb, tag, 8) == 0,
                  "read back straddling write");

            // Sparse extension: seek past EOF, write, and the gap reads zeros.
            const uint64_t far = 40ull * chunk.size() + 100000;
            check(miniext::pwrite(f, "END", 3, far) == 3, "pwrite past EOF");
            uint8_t hole[16];
            memset(hole, 0xFF, sizeof(hole));
            check(miniext::pread(f, hole, sizeof(hole), far - 1000) == sizeof(hole),
                  "read inside the hole");
            bool zeros = true;
            for (uint8_t b : hole) { if (b) zeros = false; }
            check(zeros, "hole reads as zeros");

            // Truncate down, then confirm the size and that reads clip.
            check(miniext::truncate(f, 5000) == 0, "truncate to 5000");
            check(miniext::size(f) == 5000, "size after truncate");
            uint8_t t2[16];
            check(miniext::pread(f, t2, sizeof(t2), 4996) == 4, "read clipped after truncate");

            check(miniext::sync(f) == 0, "sync");
            miniext::close(f);
        }
    }

    // Reopen and confirm the data survived the close.
    {
        uint64_t sz = 0;
        check(miniext::file_size("/db/written.bin", &sz) == 0 && sz == 5000,
              "size persists after close");
    }

    // --- namespace operations -------------------------------------------
    check(miniext::mkdir("/db/newdir") == 0, "mkdir /db/newdir");
    check(miniext::is_directory("/db/newdir"), "newdir is a directory");
    check(miniext::mkdir("/db/newdir") == -EEXIST, "mkdir twice gives EEXIST");

    {
        int err = 0;
        miniext::file *g = miniext::open("/db/newdir/inner.txt",
                                         miniext::O_RDWR | miniext::O_CREATE, &err);
        check(g != nullptr, "create a file inside newdir");
        if (g) {
            check(miniext::pwrite(g, "inner", 5, 0) == 5, "write inside newdir");
            miniext::close(g);
        }
    }
    check(miniext::rmdir("/db/newdir") == -ENOTEMPTY, "rmdir non-empty gives ENOTEMPTY");
    check(miniext::unlink("/db/newdir/inner.txt") == 0, "unlink inner.txt");
    check(miniext::rmdir("/db/newdir") == 0, "rmdir now succeeds");
    check(!miniext::exists("/db/newdir"), "newdir is gone");

    check(miniext::rename("/db/written.bin", "/db/renamed.bin") == 0, "rename");
    check(!miniext::exists("/db/written.bin"), "old name is gone");
    check(miniext::exists("/db/renamed.bin"), "new name is present");
    check(miniext::unlink("/db/renamed.bin") == 0, "unlink renamed.bin");
    check(!miniext::exists("/db/renamed.bin"), "renamed.bin is gone");

    // Many files in one directory, to force the directory to grow a block.
    {
        bool ok = true;
        for (int i = 0; i < 200; i++) {
            char name[64];
            snprintf(name, sizeof(name), "/db/many-%03d.dat", i);
            int err = 0;
            miniext::file *g = miniext::open(name, miniext::O_RDWR | miniext::O_CREATE, &err);
            if (!g) { ok = false; break; }
            miniext::pwrite(g, name, strlen(name), 0);
            miniext::close(g);
        }
        check(ok, "create 200 files in one directory");

        int seen = 0;
        miniext::list("/db", [&](const char *n, bool) {
            if (strncmp(n, "many-", 5) == 0) seen++;
        });
        check(seen == 200, "all 200 are listed");

        ok = true;
        for (int i = 0; i < 200; i++) {
            char name[64];
            snprintf(name, sizeof(name), "/db/many-%03d.dat", i);
            if (miniext::unlink(name) != 0) { ok = false; break; }
        }
        check(ok, "unlink all 200");
    }

    // --- out-of-order writes -------------------------------------------
    // Extents must stay sorted by logical block. Appending blindly works for a
    // sequential writer and corrupts the tree for anyone else: lookups then
    // miss mappings that exist and the same block gets allocated twice. DuckDB
    // writes this way, which is how the bug was found.
    {
        int err = 0;
        miniext::file *f = miniext::open("/db/ooo.bin",
                                         miniext::O_RDWR | miniext::O_CREATE, &err);
        check(f != nullptr, "create /db/ooo.bin");
        if (f) {
            const size_t bs = 4096;
            std::vector<uint8_t> blk(bs);

            // Write descending, so every write lands before the previous one.
            bool ok = true;
            for (int i = 63; i >= 0; i--) {
                memset(blk.data(), (uint8_t)(i + 1), bs);
                if (miniext::pwrite(f, blk.data(), bs, (uint64_t)i * bs) != (int64_t)bs) {
                    ok = false;
                    break;
                }
            }
            check(ok, "write 64 blocks in descending order");
            check(miniext::size(f) == 64 * bs, "size after descending writes");

            // Then a scattered pass over the same file.
            const int scatter[] = {40, 3, 61, 17, 0, 58, 22, 9};
            ok = true;
            for (int i : scatter) {
                memset(blk.data(), (uint8_t)(200 + i), bs);
                if (miniext::pwrite(f, blk.data(), bs, (uint64_t)i * bs) != (int64_t)bs) {
                    ok = false;
                    break;
                }
            }
            check(ok, "rewrite scattered blocks");

            // Every block must read back exactly what was last written to it.
            ok = true;
            for (int i = 0; i < 64 && ok; i++) {
                uint8_t want = (uint8_t)(i + 1);
                for (int j : scatter) {
                    if (j == i) {
                        want = (uint8_t)(200 + i);
                    }
                }
                if (miniext::pread(f, blk.data(), bs, (uint64_t)i * bs) != (int64_t)bs) {
                    ok = false;
                    break;
                }
                for (size_t k = 0; k < bs; k++) {
                    if (blk[k] != want) {
                        printf("        block %d byte %zu = %u, expected %u\n",
                               i, k, blk[k], want);
                        ok = false;
                        break;
                    }
                }
            }
            check(ok, "every block reads back its last written value");
            miniext::close(f);
        }
    }
    check(miniext::unlink("/db/ooo.bin") == 0, "unlink ooo.bin");

    // --- as a page cache backend ----------------------------------------
    // The same file read twice: once through pread, and once as memory. The
    // second way is what the async submit path is for, so a mismatch here is
    // either the cache or the transfers it issues, and nothing else.
    {
        int err = 0;
        miniext::file *f = miniext::open("/db/big.bin", miniext::O_RD, &err);
        check(f != nullptr, "open /db/big.bin for the cache");
        if (f) {
            mem::store *s = miniext::store_open(f);
            check(s != nullptr, "a store over big.bin");
            void *m = s ? mem::pagecache::map(*s) : nullptr;
            check(m != nullptr, "map big.bin");
            if (m) {
                check(!mem::pagecache::resident(m), "nothing is read until it is touched");

                const auto *p = static_cast<const uint8_t *>(m);
                uint64_t h = fnv1a(p, expected[1].size);
                check(h == expected[1].fnv, "the mapping checksums as the file does");
                check(mem::pagecache::resident(m), "and is resident afterwards");

                // Read ahead of any fault, and checked against the same bytes
                // taken the ordinary way.
                std::vector<uint8_t> want(65536);
                check(miniext::pread(f, want.data(), want.size(), 65536) ==
                      (int64_t)want.size(), "pread the same range");
                check(mem::pagecache::fetch(const_cast<uint8_t *>(p) + 65536,
                                            want.size()) == want.size(),
                      "fetch a range");
                check(memcmp(p + 65536, want.data(), want.size()) == 0,
                      "the fetched range is what the file holds");

                mem::pagecache::unmap(m);
            }
            miniext::store_close(s);
            miniext::close(f);
        }
    }

    // Writing through it, which is the async write path and the write-back.
    {
        int err = 0;
        miniext::file *f = miniext::open("/db/cached.bin",
                                         miniext::O_RDWR | miniext::O_CREATE, &err);
        check(f != nullptr, "create /db/cached.bin");
        if (f) {
            // A store is as big as the file was when it was made, so the file
            // has to have its size before it is mapped.
            const size_t bytes = 256 * 1024;
            std::vector<uint8_t> zero(bytes, 0);
            check(miniext::pwrite(f, zero.data(), bytes, 0) == (int64_t)bytes,
                  "give cached.bin a size");

            mem::store *s = miniext::store_open(f);
            void *m = s ? mem::pagecache::map(*s) : nullptr;
            check(m != nullptr, "map cached.bin");
            if (m) {
                auto *p = static_cast<uint8_t *>(m);
                for (size_t i = 0; i < bytes; i++) {
                    p[i] = (uint8_t)(i * 17 + 3);
                }
                check(mem::pagecache::sync(m, bytes) > 0, "sync writes it back");
                mem::pagecache::unmap(m);
            }
            miniext::store_close(s);

            // Through the filesystem, which never saw the stores at all.
            std::vector<uint8_t> back(bytes);
            bool ok = miniext::pread(f, back.data(), bytes, 0) == (int64_t)bytes;
            for (size_t i = 0; ok && i < bytes; i++) {
                ok = back[i] == (uint8_t)(i * 17 + 3);
            }
            check(ok, "pread sees what was written through the mapping");
            miniext::close(f);
        }
    }
    check(miniext::unlink("/db/cached.bin") == 0, "unlink cached.bin");

    check(miniext::sync() == 0, "final sync");
    check(miniext::umount() == 0, "umount");

    if (failures) {
        printf("======== miniext: FAILED (%d of %d checks) ========\n", failures, checks);
        return 1;
    }
    printf("======== miniext: all %d checks passed ========\n", checks);
    return 0;
}
